<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="com.testng.testAPI" duration-ms="3844" started-at="2024-08-19T14:48:31Z" finished-at="2024-08-19T14:48:35Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="3844" started-at="2024-08-19T14:48:31Z" finished-at="2024-08-19T14:48:35Z">
      <class name="com.testng.testAPI">
        <test-method status="PASS" signature="conexion_cerrada_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_cerrada_TEST" is-config="true" duration-ms="1195" started-at="2024-08-19T09:48:31Z" finished-at="2024-08-19T09:48:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_cerrada_TEST -->
        <test-method status="PASS" signature="insertPerson_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="insertPerson_TEST" duration-ms="317" started-at="2024-08-19T09:48:33Z" finished-at="2024-08-19T09:48:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertPerson_TEST -->
        <test-method status="PASS" signature="conexion_abierta_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_abierta_TEST" is-config="true" duration-ms="216" started-at="2024-08-19T09:48:33Z" finished-at="2024-08-19T09:48:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_abierta_TEST -->
        <test-method status="PASS" signature="conexion_cerrada_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_cerrada_TEST" is-config="true" duration-ms="105" started-at="2024-08-19T09:48:33Z" finished-at="2024-08-19T09:48:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_cerrada_TEST -->
        <test-method status="PASS" signature="insertPerson_parametros_TEST(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean)[pri:0, instance:com.testng.testAPI@880ec60]" name="insertPerson_parametros_TEST" duration-ms="118" started-at="2024-08-19T09:48:33Z" data-provider="data_persona" finished-at="2024-08-19T09:48:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[prueba1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pruebaa1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1111111111]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[prueba1@gmail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertPerson_parametros_TEST -->
        <test-method status="PASS" signature="conexion_abierta_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_abierta_TEST" is-config="true" duration-ms="192" started-at="2024-08-19T09:48:33Z" finished-at="2024-08-19T09:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_abierta_TEST -->
        <test-method status="PASS" signature="conexion_cerrada_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_cerrada_TEST" is-config="true" duration-ms="195" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_cerrada_TEST -->
        <test-method status="PASS" signature="insertPerson_parametros_TEST(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean)[pri:0, instance:com.testng.testAPI@880ec60]" name="insertPerson_parametros_TEST" duration-ms="92" started-at="2024-08-19T09:48:34Z" data-provider="data_persona" finished-at="2024-08-19T09:48:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[prueba2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pruebaa2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2222222222]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[prueba2@gmail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertPerson_parametros_TEST -->
        <test-method status="PASS" signature="conexion_abierta_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_abierta_TEST" is-config="true" duration-ms="204" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_abierta_TEST -->
        <test-method status="PASS" signature="conexion_cerrada_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_cerrada_TEST" is-config="true" duration-ms="78" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_cerrada_TEST -->
        <test-method status="FAIL" signature="lista_persona_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="lista_persona_TEST" duration-ms="215" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [21] but found [24]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [21] but found [24]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.testng.testAPI.lista_persona_TEST(testAPI.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lista_persona_TEST -->
        <test-method status="PASS" signature="conexion_abierta_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_abierta_TEST" is-config="true" duration-ms="76" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_abierta_TEST -->
        <test-method status="PASS" signature="conexion_cerrada_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_cerrada_TEST" is-config="true" duration-ms="190" started-at="2024-08-19T09:48:34Z" finished-at="2024-08-19T09:48:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_cerrada_TEST -->
        <test-method status="FAIL" signature="timeTestOne()[pri:0, instance:com.testng.testAPI@880ec60]" name="timeTestOne" duration-ms="530" started-at="2024-08-19T09:48:35Z" finished-at="2024-08-19T09:48:35Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.timeTestOne() didn't finish within the time-out 500]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeTestOne() didn't finish within the time-out 500
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- timeTestOne -->
        <test-method status="PASS" signature="conexion_abierta_TEST()[pri:0, instance:com.testng.testAPI@880ec60]" name="conexion_abierta_TEST" is-config="true" duration-ms="95" started-at="2024-08-19T09:48:35Z" finished-at="2024-08-19T09:48:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conexion_abierta_TEST -->
      </class> <!-- com.testng.testAPI -->
    </test> <!-- Command line test -->
  </suite> <!-- com.testng.testAPI -->
</testng-results>
